name: Publish

on:
  create:
    tags:
      - release/*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: ./node_modules/.bin/rollup -c config/rollup.config.js
      - run: ./scripts/publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
